### ISSUE TITLE
有缓存方案吗？

### ISSUE THREAD

**Issue by eallion** [Moraxyc/ai-summary-hugo#4]

**Comment by Moraxyc** [comment]
请问缓存指的是什么？这个脚本会获取summary中的generated参数来判断是否生成，已生成就直接跳过

**Comment by eallion** [comment]
对，大概就是这个意思，不然 Token 消耗太快了。

**Comment by eallion** [comment]
数据来源是以目录下的 .md 文件为准，还是要提前把 title 和 slug 写入 summary.json 文件？

**Comment by Moraxyc** [comment]
md文件为准，只要posts下有md文件，然后存在slug和title就行

**Comment by Moraxyc** [comment]
这个获取md文件是包含了子目录的遍历，可以说全自动无死角不用任何操作（

**Comment by eallion** [comment]
Good! Thanks!

**Comment by Moraxyc** [comment]
@eallion 昨天发现了CI部署方案没考虑提交更新的情况，最新的commit中的README解决了这个问题

**Comment by eallion** [comment]
其实还可以考虑设置 Proxy API。

**Comment by Moraxyc** [comment]
通过环境变量替换掉默认的openai端点？
好像意义不大，毕竟action可以直接访问

或者你指的是通过自己部署的api来获取summary而无需通过这个来请求？
那得要一个标准的返回格式吧

在2023年8月19日八月 下午7:40，Charles Chin写道：

**Comment by g0fcn** [comment]
shell: /usr/bin/bash -e {0}
  env:
    OPENAI_API_KEY: ***
    pythonLocation: /opt/hostedtoolcache/Python/3.[11](https://github.com/g0fcn/hugo-blog/actions/runs/8005078610/job/21863719825#step:5:11).4/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib
Traceback (most recent call last):
  File "/home/runner/work/hugo-blog/hugo-blog/ai-summary-hugo/main.py", line 61, in <module>
summary.json不存在, 初始化中
    main()
  File "/home/runner/work/hugo-blog/hugo-blog/ai-summary-hugo/main.py", line [23](https://github.com/g0fcn/hugo-blog/actions/runs/8005078610/job/21863719825#step:5:24), in main
    slug = post['slug']
           ~~~~^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/frontmatter/__init__.py", line 303, in __getitem__
    return self.metadata[name]
           ~~~~~~~~~~~~~^^^^^^
KeyError: 'slug'
