### ISSUE TITLE
这是啥情况啊

### ISSUE THREAD

**Issue by g0fcn** [Moraxyc/ai-summary-hugo#42]
shell: /usr/bin/bash -e {0}
  env:
    OPENAI_API_KEY: ***
    pythonLocation: /opt/hostedtoolcache/Python/3.[11](https://github.com/g0fcn/hugo-blog/actions/runs/8005078610/job/21863719825#step:5:11).4/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib
Traceback (most recent call last):
  File "/home/runner/work/hugo-blog/hugo-blog/ai-summary-hugo/main.py", line 61, in <module>
summary.json不存在, 初始化中
    main()
  File "/home/runner/work/hugo-blog/hugo-blog/ai-summary-hugo/main.py", line [23](https://github.com/g0fcn/hugo-blog/actions/runs/8005078610/job/21863719825#step:5:24), in main
    slug = post['slug']
           ~~~~^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/frontmatter/__init__.py", line 303, in __getitem__
    return self.metadata[name]
           ~~~~~~~~~~~~~^^^^^^
KeyError: 'slug'

**Comment by Moraxyc** [comment]
错误日志表明没有从post中获取到slug属性

看了下你的博客仓库，发现里面的md文件元数据没有slug，该程序需要使用slug来对应文件数据

详见hugo的文档[URL management](https://gohugo.io/content-management/urls/)

**Comment by g0fcn** [comment]
呃呃呃，没有咋搞啊

**Comment by Moraxyc** [comment]
emmmm

添加上slug？随机字符创建的短slug对seo更加友好

**Comment by Moraxyc** [comment]
建议在config.toml里这么写:

```TOML
[Permalinks]
  posts = "/post/:slug"
```

然后在posts里加上该属性的值，随机8位英文数字字符即可充当slug

**Comment by g0fcn** [comment]
啊，我文章需要一个一个加嘛

**Comment by Moraxyc** [comment]
需要
