### ISSUE TITLE
能不能优化下运行速度呀

### ISSUE THREAD

**Issue by xinkeji** [Moraxyc/ai-summary-hugo#45]
![Screenshot_2024-03-04-21-05-00-516_com.android.browser.jpg](https://github.com/Moraxyc/ai-summary-hugo/assets/33138729/f4d50b3c-384d-41bc-9249-d6a02648e801)

目前也没多少文章，能不能把已经生成的文章进程缓存起来，新增文章时，只对新增内容进行摘要啊

**Comment by Moraxyc** [comment]
缓存机制是存在的，我看了你的action日志，原因是openai设置了速率限制，导致先前某些文章没能生成成功，那么之后的action又会再次执行先前未完成的工作。

建议在本地先把所有的文章总结生成完全，再让action执行更新
